version: "3.9"

services:
  auth-service:
    build:
      context: ./auth_service
    env_file:
      - ./auth_service/.env
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - auth_data:/app/data

  bot-api:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8001:8001"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

  bot-poller:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    command: ["python", "-m", "app.main"]

  bot-worker:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    command: ["celery", "-A", "app.infra.celery_app", "worker", "--loglevel=info"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth_data: